In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
dataset = pd.read_csv('house_prices.csv')
print(dataset)
print(dataset.shape)

     house_id    sqft  bedrooms  bathrooms location  year_built  price_usd
0           1  3898.0         5          2    Galle        2003     202080
1           2  1822.0         5          4  Colombo        1988     147652
2           3  4963.0         5          2      NaN        2019     485793
3           4  2592.0         2          4      NaN        2012     158582
4           5  2938.0         3          3    Galle        2014     548258
..        ...     ...       ...        ...      ...         ...        ...
245       246  4720.0         4          1    Kandy        1987     335634
246       247  2433.0         3          4  Colombo        1988     503262
247       248  2336.0         2          4    Kandy        1998     451539
248       249  2014.0         6          1    Kandy        2000     364934
249       250  1634.0         6          3    Kandy        1990      87613

[250 rows x 7 columns]
(250, 7)


In [14]:
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[1 3898.0 5 2 'Galle' 2003]
 [2 1822.0 5 4 'Colombo' 1988]
 [3 4963.0 5 2 nan 2019]
 ...
 [248 2336.0 2 4 'Kandy' 1998]
 [249 2014.0 6 1 'Kandy' 2000]
 [250 1634.0 6 3 'Kandy' 1990]]
[202080 147652 485793 158582 548258 341759 489523 396380 188977 376762
 193515 106393 182647 194358 115621  53221 568527 327516 265146 560773
 165826 265607 514135 393937 263549 183263  59665  87629 130687 480506
 397980 282742 478426 130037 158123 259928 553741 383970 516558 178970
 515093  80588 167490 332894  68300 520626 525757 343221 211248  95419
 386593 341096 465581 377419 111844 108188 477269 129053 565566  99330
 447889 586129 287084  71759 530939 144891 335376 591340 457071  65937
 499483 130295 459637 387734 201198 277221 105992 592599 173469 212859
 321609 416533 322955 322877 366280 520310 261257 505993 480659 578163
 551366 486980 178166 473606 452453 202120 419664 181662 332930 486179
 145576 228693 485330 294123 577950  44457 444228 495951 554001 127782
 591143 259675 237148 239103 397405

In [15]:
print(dataset.isnull().sum())

house_id       0
sqft          20
bedrooms       0
bathrooms      0
location      51
year_built     0
price_usd      0
dtype: int64


In [16]:
from sklearn.impute import SimpleImputer
sqft_impute = SimpleImputer(missing_values=np.nan, strategy='mean')
sqft_impute.fit(x[:, 1:2])
x[:, 1:2] = sqft_impute.transform(x[:, 1:2])

location_impute = SimpleImputer(strategy='most_frequent')
location_impute.fit(x[:, 4:5])
x[:, 4:5] = location_impute.transform(x[:, 4:5])
print(x)


[[1 3898.0 5 2 'Galle' 2003]
 [2 1822.0 5 4 'Colombo' 1988]
 [3 4963.0 5 2 'Jaffna' 2019]
 ...
 [248 2336.0 2 4 'Kandy' 1998]
 [249 2014.0 6 1 'Kandy' 2000]
 [250 1634.0 6 3 'Kandy' 1990]]


In [17]:
print(pd.isnull(x).sum())

0


In [20]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [4])
    ],
    remainder='passthrough'
)
x = ct.fit_transform(x)
print(x)

[[0.0 1.0 0.0 ... 5 2 2003]
 [1.0 0.0 0.0 ... 5 4 1988]
 [0.0 0.0 1.0 ... 5 2 2019]
 ...
 [0.0 0.0 0.0 ... 2 4 1998]
 [0.0 0.0 0.0 ... 6 1 2000]
 [0.0 0.0 0.0 ... 6 3 1990]]


In [21]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print('x_train', x_train)
print('x_test', x_test)
print('y_train',  y_train)
print('y_test', y_test)

x_train [[1.0 0.0 0.0 ... 1 1 1998]
 [0.0 0.0 1.0 ... 6 3 2002]
 [0.0 0.0 1.0 ... 5 3 2018]
 ...
 [0.0 1.0 0.0 ... 2 4 1982]
 [0.0 0.0 0.0 ... 1 2 2024]
 [0.0 0.0 1.0 ... 1 2 1999]]
x_test [[1.0 0.0 0.0 0.0 68 1836.0 4 4 2004]
 [0.0 0.0 0.0 1.0 250 1634.0 6 3 1990]
 [1.0 0.0 0.0 0.0 231 2629.0 3 3 1998]
 [0.0 0.0 0.0 1.0 162 2599.0 5 1 1993]
 [0.0 0.0 0.0 1.0 92 2537.0 2 1 2011]
 [0.0 0.0 0.0 1.0 225 3802.0 4 4 2011]
 [0.0 0.0 0.0 1.0 59 3538.0 5 1 1985]
 [0.0 0.0 1.0 0.0 235 826.0 6 4 1991]
 [0.0 0.0 1.0 0.0 181 2460.0 2 2 2014]
 [0.0 1.0 0.0 0.0 5 2938.0 3 3 2014]
 [0.0 0.0 1.0 0.0 243 4261.0 6 1 2001]
 [1.0 0.0 0.0 0.0 189 906.0 6 3 1989]
 [0.0 0.0 0.0 1.0 117 2070.0 1 1 2019]
 [0.0 1.0 0.0 0.0 183 3326.0 3 3 2014]
 [0.0 0.0 0.0 1.0 128 691.0 2 4 2008]
 [0.0 0.0 1.0 0.0 79 4792.0 5 2 2024]
 [0.0 0.0 1.0 0.0 185 4704.0 2 1 1997]
 [0.0 1.0 0.0 0.0 52 1314.0 4 2 2020]
 [0.0 1.0 0.0 0.0 28 1433.0 1 4 1999]
 [0.0 0.0 0.0 1.0 74 4826.0 3 4 2008]
 [0.0 1.0 0.0 0.0 226 2872.0434782608695 1 

In [22]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])
print(x_train)

[[1.0 0.0 0.0 ... -1.3169658116222405 -1.3790478163325866
  -0.30014152788655624]
 [0.0 0.0 1.0 ... 1.6425079223603223 0.37212401393101524
  0.010082273546585573]
 [0.0 0.0 1.0 ... 1.0506131755638097 0.37212401393101524
  1.2509774792791528]
 ...
 [0.0 1.0 0.0 ... -0.7250710648257279 1.2477099290628162
  -1.5410367336191235]
 [0.0 0.0 0.0 ... -1.3169658116222405 -0.5034619012007857
  1.7163131814288655]
 [0.0 0.0 1.0 ... -1.3169658116222405 -0.5034619012007857
  -0.22258557752827077]]
