In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('customer_churn.csv')
print(dataset)
print(dataset.shape)
print(dataset.describe)

     customer_id  age  gender  monthly_charges  tenure_months contract_type  \
0              1   22  Female            59.16             37       Monthly   
1              2   58  Female            62.93             60        Yearly   
2              3   52    Male            59.96             28       Monthly   
3              4   40     NaN            68.05             36        Yearly   
4              5   40  Female            94.43              3        Yearly   
..           ...  ...     ...              ...            ...           ...   
195          196   22  Female            76.62             69      Two Year   
196          197   35     NaN            63.86             45        Yearly   
197          198   24  Female            61.59             56       Monthly   
198          199   35  Female            49.41             33       Monthly   
199          200   68  Female            73.61             62        Yearly   

     churn  
0        0  
1        0  
2        1  

In [3]:
x =  dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values
print(x)
print(y)

[[1 22 'Female' 59.16 37 'Monthly']
 [2 58 'Female' 62.93 60 'Yearly']
 [3 52 'Male' 59.96 28 'Monthly']
 ...
 [198 24 'Female' 61.59 56 'Monthly']
 [199 35 'Female' 49.41 33 'Monthly']
 [200 68 'Female' 73.61 62 'Yearly']]
[0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0
 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1
 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1]


In [4]:
import pandas as pd

x_df = pd.DataFrame(
    x,
    columns=[
        'customer_id',
        'age',
        'gender',
        'monthly_charges',
        'tenure_months',
        'contract_type'
    ]
)

print(x_df.head())

  customer_id age  gender monthly_charges tenure_months contract_type
0           1  22  Female           59.16            37       Monthly
1           2  58  Female           62.93            60        Yearly
2           3  52    Male           59.96            28       Monthly
3           4  40     NaN           68.05            36        Yearly
4           5  40  Female           94.43             3        Yearly


In [5]:
print(dataset.isnull().sum())

customer_id         0
age                 0
gender              8
monthly_charges    15
tenure_months       0
contract_type      11
churn               0
dtype: int64


In [6]:
from sklearn.impute import SimpleImputer

gender_imputer = SimpleImputer(strategy='most_frequent')
x[:, 2:3] = gender_imputer.fit_transform(x[:, 2:3])

monthly_imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, 3:4] = monthly_imputer.fit_transform(x[:, 3:4])

contract_imputer = SimpleImputer(strategy='most_frequent')
x[:, 5:6] = contract_imputer.fit_transform(x[:, 5:6])
print(x)

[[1 22 'Female' 59.16 37 'Monthly']
 [2 58 'Female' 62.93 60 'Yearly']
 [3 52 'Male' 59.96 28 'Monthly']
 ...
 [198 24 'Female' 61.59 56 'Monthly']
 [199 35 'Female' 49.41 33 'Monthly']
 [200 68 'Female' 73.61 62 'Yearly']]


In [7]:
print(pd.isnull(x).sum())

0


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ('encoder', OneHotEncoder(), [2, 5])
    ],
    remainder='passthrough'
)

x = ct.fit_transform(x)

print(x)

[[1.0 0.0 1.0 ... 22 59.16 37]
 [1.0 0.0 0.0 ... 58 62.93 60]
 [0.0 1.0 1.0 ... 52 59.96 28]
 ...
 [1.0 0.0 1.0 ... 24 61.59 56]
 [1.0 0.0 1.0 ... 35 49.41 33]
 [1.0 0.0 0.0 ... 68 73.61 62]]


In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 0 1 0 0 1 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0
 0 1 0 0 0 1 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 1 0 0 0 0 1 0 0 1 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1
 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 0 1 0 0 0 1 0 0 0 0 0 0 0 1]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print('x_train', x_train)
print('x_test', x_test)
print('y_train',  y_train)
print('y_test', y_test)

x_train [[0.0 1.0 1.0 ... 42 80.2 20]
 [1.0 0.0 0.0 ... 52 67.76 6]
 [0.0 1.0 1.0 ... 33 65.62864864864865 55]
 ...
 [0.0 1.0 1.0 ... 42 61.95 57]
 [1.0 0.0 1.0 ... 69 37.36 22]
 [1.0 0.0 0.0 ... 61 79.62 26]]
x_test [[1.0 0.0 0.0 0.0 1.0 59 56 65.62864864864865 54]
 [1.0 0.0 0.0 0.0 1.0 41 26 41.56 6]
 [1.0 0.0 0.0 1.0 0.0 35 64 88.42 48]
 [1.0 0.0 1.0 0.0 0.0 103 59 18.8 71]
 [1.0 0.0 1.0 0.0 0.0 185 43 59.31 57]
 [1.0 0.0 1.0 0.0 0.0 199 35 49.41 33]
 [0.0 1.0 1.0 0.0 0.0 96 32 39.97 4]
 [1.0 0.0 0.0 0.0 1.0 5 40 94.43 3]
 [1.0 0.0 0.0 0.0 1.0 30 41 51.05 27]
 [0.0 1.0 0.0 1.0 0.0 169 35 86.52 50]
 [0.0 1.0 0.0 1.0 0.0 172 22 64.48 22]
 [0.0 1.0 1.0 0.0 0.0 19 61 58.31 52]
 [0.0 1.0 1.0 0.0 0.0 12 68 71.56 4]
 [0.0 1.0 0.0 0.0 1.0 90 61 24.93 11]
 [1.0 0.0 1.0 0.0 0.0 111 32 75.6 60]
 [1.0 0.0 1.0 0.0 0.0 119 30 62.65 57]
 [1.0 0.0 1.0 0.0 0.0 160 58 58.37 13]
 [0.0 1.0 1.0 0.0 0.0 36 21 80.02 9]
 [0.0 1.0 1.0 0.0 0.0 137 49 65.62864864864865 27]
 [1.0 0.0 0.0 1.0 0.0 60 53 65.62864