Importing Libraries 
when building machinery models we just need to import the relevant libraries we need. Here we import three libraries
1. Numpy - work with arrays - because most of the machine learning models accepts input as an arrays
2. Pandas - import data sets , create matrix of features and depended variable vector
3. Matplotlib - plot nice charts

Scikit learn simply creating object from classes


In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
import os
print(os.listdir('/content/drive/MyDrive'))

['Chethana Virajini-CV (1).pdf', 'Chethana Virajini-CV.pdf', 'medfrontend-react', 'Colab Notebooks', 'Chethana Virajini.pdf', 'React 50 important questions .pdf', 'React Important Questions .pdf', 'stagedevmed_devauadmin_medfuture (4).sql', 'Referee Details.docx', 'Next.js 15 Crash Course _ Build and Deploy a Production-Ready Full Stack App.mp4', 'How To Build A $1,000,000 SaaS In 7 Hours.mp4', 'index.php', 'meta.php', 'New folder (2)', 'Next.js Full-Stack School Management App Full Tutorial _ Role Based School Dashboard Project.mp4', 'response.json', 'responseall.json', 'udemy', 'Jaya Piritha, Maha Mangala Suthraya, Rathana Suthraya, Karaniya Meththa Suthraya  ජය පිරිත, මංගල.mp4', 'Kubera Mantra 108 Times With Lyrics _ Kubera Mantra To Attract Money, Wealth & Cash _ कुबेर मंत्रा.mp4', 'නිකොලා ටෙස්ලා 369Hz Binauralභාවනාව ඔබේ ජීවිතය මුදල් බහුලත්වය, පුද්ගල ආකර්ශණය ධනාත්මක බවට දින 21අහන්න.mp4', 'Relaxing Theta Waves (15 min) - Binaural Beats - Slow Down Your Brainwaves.mp4', 'The BEST K

Import Datasets

when importing a dataset first we need to cerate new variable and then we need to integrate with real dataset into that variable. pandas library has certain functions to read of values from datasets and will create data frame. it is a certain format of dataset

In [4]:
dataset = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Data.csv')
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


This is not enough when processing data , need to cerate two new entities
1. matrix of features - columns which are going to predict the dependent variable
2. depended variable vector - anyway this is output
we use iloc function from pandas library which is stand for locating indexes.
here dataset will convert into the two matrixes
lowerbound : upperbound

In [5]:
x = dataset.iloc[:, :-1].values
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [6]:

y = dataset.iloc[:, -1].values
print(y)


['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking Care of Missing Data
there is two ways of handling this
1. removing the missing data, but this will be okay if the percentage of the missing values of dataset is low
2. replacing the missing values with the average of that column

scikit-learn is python library which contain lot of tools for preprocessing data
SimpleImputer is a preprocessing utility used to handle missing values. With strategy='mean', it computes the average of each selected numerical column during fit() and replaces missing values with those averages during transform()

In [7]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])
print(x)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


Encoding Categorical Data
machine learning models work with numbers, when dataset contains string input or output we need to convert them from string to numbers
we need carefully do this otherwise misinterpretation can be occur.
one-hot encoding - consists of creating binary vectors of each category
ex: France [100]
    Spain [010]
    Germany [001]
    there is no numerical order among these three countries
    otherwise if we take 1,2,3 it means there is a order

Encoding Independent Variables - use two classes from scikit-learn library
1. column transformer class from compose module
2. one hot encoded class from pre-processing module
ColumnTransformer applies preprocessing to specific columns. Here, OneHotEncoder is applied to the first column to convert categorical values into binary indicator features, while the remaining columns are passed through unchanged. The result is a fully numerical feature matrix suitable for machine learning algorithms.


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding dependent variable
yes / no = 1/0 
there is a method called Label encoding

In [9]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting Dataset into training and test sets

Feature Scaling should apply after splitting dataset into training and test
feature scaling simply consists all variables and features to make sure all values take in the same scale 
Test set need to be a brand new set to evaluate the model
80% training set
20% test set

In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)
print('x_train', x_train)
print('x_test', x_test)
print('y_train',  y_train)
print('y_test', y_test)

x_train [[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]
x_test [[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]
y_train [0 1 0 0 1 1 0 1]
y_test [0 1]


Feature Scaling - not all machine learning models don't need this.
KNN, SVM, & Neural Network
Normalization and Standardization
Normalization applies when features having normal distribution
Standardization works for all the scenarios
feature scaling apply only for numerical values not dummy variables 

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])
print(x_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


here in the results you can see training data will be in same scale

In [12]:
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
